### PR TITLE
added convenience methods to HeiEntry

### PR DESCRIPTION
**Pull request by georgschermann**
method for easier retrieval of native name

### CODE REVIEW

**Comment by wrygiel** [comment]
You used a couple of tabs in your files, that's why the build failed. I'll fix it.

**Comment by wrygiel** [comment]
What if someone gives a `<name>`, but without any `xml:lang`? Do we assume it's in English, or in "other language"?

**Comment by wrygiel** [comment]
> What if someone gives a `<name>`, but without any `xml:lang`? Do we assume it's in English, or in "other language"?

I have assumed this would be "other language".

Merged your changes, with some modifications in naming and added tests.

**Comment by wrygiel** [comment]
Released as version 1.3.0. Should be available in Maven Central in a couple of minutes/hours.

**Comment by wrygiel** [comment]
BTW, this code is not 100% safe. `xml:lang` may contain something like `en-Latn` or `EN` (both are valid, according to the specs), and your code won't detect them. But I think it's a minor issue.

**Comment by wrygiel** [comment]
> BTW, this code is not 100% safe. `xml:lang` may contain something like `en-Latn` or `EN` (both are valid, according to the specs), and your code won't detect them. But I think it's a minor issue.

Fixed that too (in `1.3.1`).

**Comment by georgschermann** [comment]
thanks,
I sticked to the implementation of the primaryName.

2017-04-27 13:35 GMT+02:00 Wojciech Rygielski <notifications@github.com>:

**Pull request closed without merging**
